feat(UH-001): add Client List
exlusive-browser/exclusive-crm pull request #3
Opened 2024-11-03 14:27 UTC by AlejandroSalas1143

![image](https://github.com/user-attachments/assets/787bd93c-d38b-468a-8db6-6a4edc2dd841)
![image](https://github.com/user-attachments/assets/4edc54a5-7abf-4fb3-b0fc-78b46ab4c4d4)

2024-11-03 20:23 UTC, dgop92 requested changes
looks great, but the details action on the table is missing, how do you travel to client details?

2024-11-03 22:27 UTC, dgop92 approved these changes
ok

2024-11-03 22:28 UTC, ndelarans approved these changes
Ok

2024-11-04 02:34 UTC, sebastian0327 approved these changes
looks great

2024-11-04 03:01 UTC, merged