Add Header and Subheader
exlusive-browser/exclusive-crm pull request #5
Opened 2024-11-04 14:42 UTC by ndelarans

![image](https://github.com/user-attachments/assets/74242a14-81f6-4cec-8f1d-a035f3d739c8)
_**Responsive**_
![image](https://github.com/user-attachments/assets/8ffb86ba-2ad7-4c28-9d47-e58365d756e8)
![image](https://github.com/user-attachments/assets/81239580-7718-4c11-888a-f36f36413604)

2024-11-04 19:43 UTC, dgop92 requested changes
Overall is good, but there are some important things to fix

2024-11-04 19:43 UTC, dgop92 commented on src/common-pages/Subheader.tsx
> +        window.history.pushState(null, '', `/${item}`);
I belive this strategy does not work, take a look of https://mui.com/material-ui/react-link/

2024-11-04 19:43 UTC, dgop92 commented on src/common-pages/Subheader.tsx
> +                <div style={{ display: 'flex', flexDirection: 'row', justifyContent: isMobile ? 'flex-start' : 'space-between' }}>
Research about the sx prop and mui breakpoints, your approach is not optimal

2024-11-05 00:57 UTC, AlejandroSalas1143 approved these changes
ok

2024-11-05 01:07 UTC, merged