Feature/uh 004 update clients
exlusive-browser/exclusive-crm pull request #7
Opened 2024-11-04 19:32 UTC by sebastian0327

![image](https://github.com/user-attachments/assets/4bed9eef-9d9d-4fc7-a65a-65fd0c8bf9c7)
![image](https://github.com/user-attachments/assets/400a47b2-3fd7-49e4-aeb7-69cdf01137de)
![image](https://github.com/user-attachments/assets/f8d14b64-41c4-4e50-9667-cb875635f88f)

2024-11-04 19:56 UTC, dgop92 requested changes
look at the comments

2024-11-04 19:56 UTC, dgop92 commented on src/features/client/entities/client.ts
> +        .max(255, "Phone is too long"),
email does not have it's corresponding validations

2024-11-04 19:56 UTC, dgop92 commented on src/features/client/pages/ClientUpdate/useUpadteClient.ts
> +        "Client is updated successfully",
i think it is "was updated"

2024-11-05 01:19 UTC, dgop92 approved these changes
ok

2024-11-05 01:22 UTC, ndelarans approved these changes
Ok

2024-11-05 01:33 UTC, AlejandroSalas1143 approved these changes
OK

2024-11-05 01:46 UTC, merged